// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import android.support.annotation.NonNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public final class OrderCompleted extends PropertiesSerializable {
    private Properties properties;

    private OrderCompleted(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link OrderCompleted}
     */
    public static class Builder {
        private static String AFFILIATION_KEY = "affiliation";
        private static String CHECKOUT_ID_KEY = "checkout_id";
        private static String COUPON_KEY = "coupon";
        private static String CURRENCY_KEY = "currency";
        private static String DISCOUNT_KEY = "discount";
        private static String ORDER_ID_KEY = "order_id";
        private static String PRODUCTS_KEY = "products";
        private static String REVENUE_KEY = "revenue";
        private static String SHIPPING_KEY = "shipping";
        private static String TAX_KEY = "tax";
        private static String TOTAL_KEY = "total";

        private Properties properties;

        /**
         * Builder for {@link OrderCompleted}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Store or affiliation from which this transaction occurred (e.g. Google Store)
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder affiliation(final @NonNull String affiliation) {
            properties.putValue(AFFILIATION_KEY, affiliation);
            return this;
        }

        /**
         * Checkout ID
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder checkoutID(final @NonNull String checkoutID) {
            properties.putValue(CHECKOUT_ID_KEY, checkoutID);
            return this;
        }

        /**
         * Transaction coupon redeemed with the transaction
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder coupon(final @NonNull String coupon) {
            properties.putValue(COUPON_KEY, coupon);
            return this;
        }

        /**
         * Currency code associated with the transaction
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder currency(final @NonNull String currency) {
            properties.putValue(CURRENCY_KEY, currency);
            return this;
        }

        /**
         * Total discount associated with the transaction
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder discount(final @NonNull Double discount) {
            properties.putValue(DISCOUNT_KEY, discount);
            return this;
        }

        /**
         * Order/transaction ID
         * This property is required to generate a valid OrderCompleted object
         */
        public Builder orderID(final @NonNull String orderID) {
            properties.putValue(ORDER_ID_KEY, orderID);
            return this;
        }

        /**
         * Products in the order
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder products(final @NonNull List<Product> products) {
            properties.putValue(PRODUCTS_KEY, PropertiesSerializable.toPropertyList(products));
            return this;
        }

        /**
         * Revenue associated with the transaction (excluding shipping and tax)
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder revenue(final @NonNull Double revenue) {
            properties.putValue(REVENUE_KEY, revenue);
            return this;
        }

        /**
         * Shipping cost associated with the transaction
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder shipping(final @NonNull Double shipping) {
            properties.putValue(SHIPPING_KEY, shipping);
            return this;
        }

        /**
         * Total tax associated with the transaction
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder tax(final @NonNull Double tax) {
            properties.putValue(TAX_KEY, tax);
            return this;
        }

        /**
         * Revenue with discounts and coupons added in. Note that our Google Analytics Ecommerce
         * destination accepts total or revenue, but not both. For better flexibility and total
         * control over tracking, we let you decide how to calculate how coupons and discounts are
         * applied
         * This property is optional and not required to generate a valid OrderCompleted object
         */
        public Builder total(final @NonNull Double total) {
            properties.putValue(TOTAL_KEY, total);
            return this;
        }

        /**
         * Build an instance of {@link OrderCompleted}
         * Performs runtime validation on the following required properties:
         *  - orderID
         */
        public OrderCompleted build() {
            if (properties.get(ORDER_ID_KEY) == null) {
                throw new IllegalArgumentException("OrderCompleted missing required property: orderID");
            }

            return new OrderCompleted(properties);
        }
    }
}
