// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import android.support.annotation.NonNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public final class OptionalObject extends PropertiesSerializable {
    private Properties properties;

    private OptionalObject(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link OptionalObject}
     */
    public static class Builder {
        private static String OPTIONAL_SUB-PROPERTY_KEY = "optional sub-property";
        private static String REQUIRED_SUB-PROPERTY_KEY = "required sub-property";

        private Properties properties;

        /**
         * Builder for {@link OptionalObject}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Optional sub-property
         * This property is optional and not required to generate a valid OptionalObject object
         */
        public Builder optionalSubProperty(final @NonNull String optionalSubProperty) {
            properties.putValue(OPTIONAL_SUB-PROPERTY_KEY, optionalSubProperty);
            return this;
        }

        /**
         * Required sub-property
         * This property is required to generate a valid OptionalObject object
         */
        public Builder requiredSubProperty(final @NonNull String requiredSubProperty) {
            properties.putValue(REQUIRED_SUB-PROPERTY_KEY, requiredSubProperty);
            return this;
        }

        /**
         * Build an instance of {@link OptionalObject}
         * Performs runtime validation on the following required properties:
         *  - requiredSubProperty
         */
        public OptionalObject build() {
            if (properties.get(REQUIRED_SUB-PROPERTY_KEY) == null) {
                throw new IllegalArgumentException("OptionalObject missing required property: requiredSubProperty");
            }

            return new OptionalObject(properties);
        }
    }
}
