// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import android.support.annotation.NonNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public final class OptionalArray extends PropertiesSerializable {
    private Properties properties;

    private OptionalArray(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link OptionalArray}
     */
    public static class Builder {
        private static String OPTIONAL_SUB_PROPERTY_KEY = "optional sub-property";
        private static String REQUIRED_SUB_PROPERTY_KEY = "required sub-property";

        private Properties properties;

        /**
         * Builder for {@link OptionalArray}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Optional sub-property
         * This property is optional and not required to generate a valid OptionalArray object
         */
        public Builder optionalSubProperty(final @NonNull String optionalSubProperty) {
            properties.putValue(OPTIONAL_SUB_PROPERTY_KEY, optionalSubProperty);
            return this;
        }

        /**
         * Required sub-property
         * This property is required to generate a valid OptionalArray object
         */
        public Builder requiredSubProperty(final @NonNull String requiredSubProperty) {
            properties.putValue(REQUIRED_SUB_PROPERTY_KEY, requiredSubProperty);
            return this;
        }

        /**
         * Build an instance of {@link OptionalArray}
         * Performs runtime validation on the following required properties:
         *  - requiredSubProperty
         */
        public OptionalArray build() {
            if (properties.get(REQUIRED_SUB_PROPERTY_KEY) == null) {
                throw new IllegalArgumentException("OptionalArray missing required property: requiredSubProperty");
            }

            return new OptionalArray(properties);
        }
    }
}
