/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import "SEGGarage.h"

@implementation SEGGarage

+(nonnull instancetype) initWithTunnel:(nonnull SEGTunnel *)tunnel {
  SEGGarage *object = [[SEGGarage alloc] init];
  object.tunnel = tunnel;
  return object;
}

-(nonnull SERIALIZABLE_DICT) toDictionary {
  NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
  if (self.tunnel != nil) {
    properties[@"tunnel"] = [self.tunnel toDictionary];
  }

  return properties;
}

@end
