/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import <Foundation/Foundation.h>
#import <Analytics/SEGSerializableValue.h>
#import "SEGTypewriterSerializable.h"
#import "SEGTypewriterUtils.h"

@interface SEGRequiredArrayWithPropertiesItem1 : NSObject<SEGTypewriterSerializable>

/// Required any property
@property (strong, nonatomic, nonnull) id requiredAny;
/// Required array property
@property (strong, nonatomic, nonnull) NSArray<id> *requiredArray;
/// Required boolean property
@property (nonatomic) BOOL requiredBoolean;
/// Required integer property
@property (nonatomic) NSInteger requiredInt;
/// Required number property
@property (strong, nonatomic, nonnull) NSNumber *requiredNumber;
/// Required object property
@property (strong, nonatomic, nonnull) SERIALIZABLE_DICT requiredObject;
/// Required string property
@property (strong, nonatomic, nonnull) NSString *requiredString;
/// Required string property with a regex conditional
@property (strong, nonatomic, nonnull) NSString *requiredStringWithRegex;

+(nonnull instancetype) initWithRequiredAny:(nullable id)requiredAny
requiredArray:(nonnull NSArray<id> *)requiredArray
requiredBoolean:(BOOL)requiredBoolean
requiredInt:(NSInteger)requiredInt
requiredNumber:(nonnull NSNumber *)requiredNumber
requiredObject:(nonnull SERIALIZABLE_DICT)requiredObject
requiredString:(nonnull NSString *)requiredString
requiredStringWithRegex:(nonnull NSString *)requiredStringWithRegex;

-(nonnull SERIALIZABLE_DICT) toDictionary;

@end
