/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import "SEGRequiredArrayWithPropertiesItem1.h"

@implementation SEGRequiredArrayWithPropertiesItem1

+(nonnull instancetype) initWithRequiredAny:(nullable id)requiredAny
requiredArray:(nonnull NSArray<id> *)requiredArray
requiredBoolean:(BOOL)requiredBoolean
requiredInt:(NSInteger)requiredInt
requiredNumber:(nonnull NSNumber *)requiredNumber
requiredObject:(nonnull SERIALIZABLE_DICT)requiredObject
requiredString:(nonnull NSString *)requiredString
requiredStringWithRegex:(nonnull NSString *)requiredStringWithRegex {
  SEGRequiredArrayWithPropertiesItem1 *object = [[SEGRequiredArrayWithPropertiesItem1 alloc] init];
  object.requiredAny = requiredAny;
  object.requiredArray = requiredArray;
  object.requiredBoolean = requiredBoolean;
  object.requiredInt = requiredInt;
  object.requiredNumber = requiredNumber;
  object.requiredObject = requiredObject;
  object.requiredString = requiredString;
  object.requiredStringWithRegex = requiredStringWithRegex;
  return object;
}

-(nonnull SERIALIZABLE_DICT) toDictionary {
  NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
  properties[@"required any"] = self.requiredAny == nil ? [NSNull null] : self.requiredAny;
  if (self.requiredArray != nil) {
    properties[@"required array"] = [SEGTypewriterUtils toSerializableArray:self.requiredArray];
  }
  properties[@"required boolean"] = [NSNumber numberWithBool:self.requiredBoolean];
  properties[@"required int"] = [NSNumber numberWithInteger:self.requiredInt];
  if (self.requiredNumber != nil) {
    properties[@"required number"] = self.requiredNumber;
  }
  if (self.requiredObject != nil) {
    properties[@"required object"] = self.requiredObject;
  }
  if (self.requiredString != nil) {
    properties[@"required string"] = self.requiredString;
  }
  if (self.requiredStringWithRegex != nil) {
    properties[@"required string with regex"] = self.requiredStringWithRegex;
  }

  return properties;
}

@end
