// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import java.util.*;
import android.support.annotation.NonNull;

public final class OptionalArray {
    private Properties properties;

    private OptionalArray(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link OptionalArray}
     */
    public static class Builder {
        private Properties properties;

        /**
         * Builder for {@link OptionalArray}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Optional sub-property
         * This property is optional and not required to generate a valid OptionalArray object
         */
        public Builder optionalSubProperty(final @NonNull String optionalSubProperty) {
            properties.putValue("optional sub-property", optionalSubProperty);
            return this;
        }

        /**
         * Required sub-property
         * This property is required to generate a valid OptionalArray object
         */
        public Builder requiredSubProperty(final @NonNull String requiredSubProperty) {
            properties.putValue("required sub-property", requiredSubProperty);
            return this;
        }

        /**
         * Build an instance of {@link OptionalArray}
         * Performs runtime validation on the following required properties:
         *  - requiredSubProperty
         */
        public OptionalArray build() {
            if (properties.get("required sub-property") == null) {
                throw new IllegalArgumentException("OptionalArray missing required property: requiredSubProperty");
            }

            return new OptionalArray(properties);
        }
    }
}
