// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import java.util.*;
import com.segment.analytics.Properties;
import android.support.annotation.NonNull;

public final class The42_TerribleEventName3 {
    private Properties properties;

    private The42_TerribleEventName3(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link The42_TerribleEventName3}
     */
    public static class Builder {
        private Properties properties;

        /**
         * Builder for {@link The42_TerribleEventName3}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Really, don't do this.
         * This property is optional and not required to generate a valid The42_TerribleEventName3 object
         */
        public Builder the0000TerriblePropertyName3(final @NonNull Object the0000TerriblePropertyName3) {
            properties.putValue("0000---terrible-property-name~!3", the0000TerriblePropertyName3);
            return this;
        }

        /**
         * AcronymStyle bug fixed in v5.0.1
         * This property is optional and not required to generate a valid The42_TerribleEventName3 object
         */
        public Builder the42_TerribleEventName3_IdentifierID(final @NonNull Object the42_TerribleEventName3_IdentifierID) {
            properties.putValue("identifier_id", the42_TerribleEventName3_IdentifierID);
            return this;
        }

        /**
         * Duplicate key error in Android
         * This property is optional and not required to generate a valid The42_TerribleEventName3 object
         */
        public Builder identifierID(final @NonNull Object identifierID) {
            properties.putValue("identifierId", identifierID);
            return this;
        }

        /**
         * Build an instance of {@link The42_TerribleEventName3}
         */
        public The42_TerribleEventName3 build() {
            return new The42_TerribleEventName3(properties);
        }
    }
}
