/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import "SEGUniverse.h"

@implementation SEGUniverse

+(nonnull instancetype) initWithName:(nonnull NSString *)name
occupants:(nonnull NSArray<SEGOccupantsItem *> *)occupants {
  SEGUniverse *object = [[SEGUniverse alloc] init];
  object.name = name;
  object.occupants = occupants;
  return object;
}

-(nonnull SERIALIZABLE_DICT) toDictionary {
  NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
  if (self.name != nil) {
    properties[@"name"] = self.name;
  }
  if (self.occupants != nil) {
    properties[@"occupants"] = [SEGTypewriterUtils toSerializableArray:self.occupants];
  }

  return properties;
}

@end
