/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

import Foundation

class Garage: TypewriterSerializable {
  var tunnel: Tunnel

  init(tunnel: Tunnel) {
    self.tunnel = tunnel
  }

  func serializableDictionary() -> [String: Any] {
    var properties = [String: Any]()
  properties["tunnel"] = self.tunnel.serializableDictionary();

    return properties;
  }
}