/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import <Foundation/Foundation.h>
#import <Analytics/SEGSerializableValue.h>
#import "SEGTypewriterSerializable.h"
#import "SEGTypewriterUtils.h"
#import "SEGOccupantsItem.h"

@interface SEGUniverse : NSObject<SEGTypewriterSerializable>

/// The common name of this universe.
@property (strong, nonatomic, nullable) NSString *name;
/// The most important occupants in this universe.
@property (strong, nonatomic, nullable) NSArray<SEGOccupantsItem *> *occupants;

+(nonnull instancetype) initWithName:(nonnull NSString *)name
occupants:(nonnull NSArray<SEGOccupantsItem *> *)occupants;

-(nonnull SERIALIZABLE_DICT) toDictionary;

@end
