/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

#import "SEGUniverseCharactersItemItem.h"

@implementation SEGUniverseCharactersItemItem

+(nonnull instancetype) initWithName:(nonnull NSString *)name {
  SEGUniverseCharactersItemItem *object = [[SEGUniverseCharactersItemItem alloc] init];
  object.name = name;
  return object;
}

-(nonnull SERIALIZABLE_DICT) toDictionary {
  NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
  if (self.name != nil) {
    properties[@"name"] = self.name;
  }

  return properties;
}

@end
