/**
 * This client was automatically generated by Segment Typewriter. ** Do Not Edit **
 */

import Foundation

class Tunnel: TypewriterSerializable {
    var subterraneanLab: SubterraneanLab

    init(subterraneanLab: SubterraneanLab) {
        self.subterraneanLab = subterraneanLab
    }

    func serializableDictionary() -> [String: Any] {
        var properties = [String: Any]()
        properties["subterranean lab"] = self.subterraneanLab.serializableDictionary();

        return properties;
    }
}