// This code is auto-generated by Segment Typewriter. Do not edit.
package com.segment.analytics;

import java.util.*;
import android.support.annotation.NonNull;

public final class Product {
    private Properties properties;

    private Product(Properties properties) {
        this.properties = properties;
    }

    protected Properties toProperties() {
        return properties;
    }

    /**
     * Builder for {@link Product}
     */
    public static class Builder {
        private Properties properties;

        /**
         * Builder for {@link Product}
         */
        public Builder() {
            properties = new Properties();
        }

        /**
         * Brand associated with the product
         * This property is optional and not required to generate a valid Product object
         */
        public Builder brand(final @NonNull String brand) {
            properties.putValue("brand", brand);
            return this;
        }

        /**
         * Product category being viewed
         * This property is optional and not required to generate a valid Product object
         */
        public Builder category(final @NonNull String category) {
            properties.putValue("category", category);
            return this;
        }

        /**
         * Coupon code associated with a product (e.g MAY_DEALS_3)
         * This property is optional and not required to generate a valid Product object
         */
        public Builder coupon(final @NonNull String coupon) {
            properties.putValue("coupon", coupon);
            return this;
        }

        /**
         * Image url of the product
         * This property is optional and not required to generate a valid Product object
         */
        public Builder imageURL(final @NonNull String imageURL) {
            properties.putValue("image_url", imageURL);
            return this;
        }

        /**
         * Name of the product being viewed
         * This property is optional and not required to generate a valid Product object
         */
        public Builder name(final @NonNull String name) {
            properties.putValue("name", name);
            return this;
        }

        /**
         * Position in the product list (ex. 3)
         * This property is optional and not required to generate a valid Product object
         */
        public Builder position(final @NonNull Long position) {
            properties.putValue("position", position);
            return this;
        }

        /**
         * Price of the product being viewed
         * This property is optional and not required to generate a valid Product object
         */
        public Builder price(final @NonNull Double price) {
            properties.putValue("price", price);
            return this;
        }

        /**
         * Database id of the product being viewed
         * This property is optional and not required to generate a valid Product object
         */
        public Builder productID(final @NonNull String productID) {
            properties.putValue("product_id", productID);
            return this;
        }

        /**
         * Quantity of a product
         * This property is optional and not required to generate a valid Product object
         */
        public Builder quantity(final @NonNull Double quantity) {
            properties.putValue("quantity", quantity);
            return this;
        }

        /**
         * Sku of the product being viewed
         * This property is optional and not required to generate a valid Product object
         */
        public Builder sku(final @NonNull String sku) {
            properties.putValue("sku", sku);
            return this;
        }

        /**
         * URL of the product page
         * This property is optional and not required to generate a valid Product object
         */
        public Builder url(final @NonNull String url) {
            properties.putValue("url", url);
            return this;
        }

        /**
         * Variant of the product (e.g. Black)
         * This property is optional and not required to generate a valid Product object
         */
        public Builder variant(final @NonNull String variant) {
            properties.putValue("variant", variant);
            return this;
        }

        /**
         * Build an instance of {@link Product}
         */
        public Product build() {
            return new Product(properties);
        }
    }
}
