name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  cancel_previous:
    runs-on: ubuntu-latest-large
    steps:
    - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b  # 0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
  build-and-test:
    name: "Test (Node.js v${{ matrix.node-version }})"
    needs: cancel_previous
    runs-on: ubuntu-latest-large
    strategy:
      matrix:
        node-version: [ 18, 20, 21 ]
    steps: 
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --coverage
